CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,idempotency_key TEXT UNIQUE NOT NULL,email TEXT NOT NULL,customer TEXT NOT NULL,items TEXT NOT NULL,total INTEGER NOT NULL,shipping INTEGER,status TEXT NOT NULL DEFAULT 'Primljena',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS subscribers(email TEXT PRIMARY KEY,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS catalog_products(id TEXT PRIMARY KEY,data TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admins(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,totp_secret TEXT,totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_sessions(token_hash TEXT PRIMARY KEY,admin_id BIGINT NOT NULL REFERENCES admins(id),expires_at BIGINT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires BIGINT NOT NULL);